services:
  - type: web
    name: smartphone-alerts-server-2
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: '*'
